name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_python_38:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install expect
      run: sudo apt-get update && sudo apt-get install -y expect
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run evaluate.py and check correct_ratio
      run: |
        export PYTHONPATH=.
        output=$(python3 RAGnews/evaluate.py --data "hairy-trumpet/data/wiki__page=2024_United_States_presidential_election,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]")
        correct_ratio=$(echo "$output" | grep -oP 'Correct Ratio: \K[0-9.]+')
        if (( $(echo "$correct_ratio > 0.7" | bc -l) )); then
          echo "Test passed"
        else
          echo "Test failed"
          exit 1
        fi
  test_python_39:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install expect
      run: sudo apt-get update && sudo apt-get install -y expect
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run evaluate.py and check correct_ratio
      run: |
        export PYTHONPATH=.
        output=$(python3 RAGnews/evaluate.py --data "hairy-trumpet/data/wiki__page=2024_United_States_presidential_election,recursive_depth=0__dpsize=paragraph,transformations=[canonicalize, group, rmtitles, split]")
        correct_ratio=$(echo "$output" | grep -oP 'Correct Ratio: \K[0-9.]+')
        if (( $(echo "$correct_ratio > 0.7" | bc -l) )); then
          echo "Test passed"
        else
          echo "Test failed"
          exit 1
        fi